org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

parchment_minecraft_version=1.21.5
parchment_mappings_version=2025.06.15
minecraft_version=1.21.5
minecraft_version_range=[1.21.5,1.21.6)
neo_version=21.5.80
neo_version_range=[21.5.0,)
loader_version_range=[4,)

mod_id=sophisticatedbackpackscreateintegration
mod_name=Sophisticated Backpacks Create Integration
mod_license=All Rights Reserved
mod_version=0.1.5
mod_group_id=sophisticatedbackpackscreateintegration
mod_authors=P3pp3rF1y
mod_description=Full Featured Sophisticated Backpacks on Create Contraptions
mod_credits=Created by P3pp3rF1y.
mod_logo_file=logo.png
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks-create-integration
mod_issue_tracker_url=https://github.com/P3pp3rF1y/SophisticatedBackpacksCreateIntegration/issues
sonar_project_key=sophisticatedbackpackscreateintegration:SophisticatedBackpacksCreateIntegration
github_package_url=https://maven.pkg.github.com/P3pp3rF1y/SophisticatedBackpacksCreateIntegration

jei_mc_version=1.21.5-neoforge
jei_version=21.3.0.18
emi_version=1.1.22+1.21.1
rei_version=19.0.806
create_mc_version=1.21.1
create_version=6.0.7-159
flywheel_version=1.0.5-32
ponder_version=1.0.63
sc_version=[1.21.5-1.3.89,1.21.6)
sb_version=[1.21.5-3.25.13,1.21.6)

#publish
curseforge_id=1238567
release_type=release
release_versions=1.21.5
modrinth_project_id=s85zLEDe