# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the minecraft version (without the 1.)
loaderVersion="${loader_version_range}" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="" #optional

# A URL to refer people to when problems occur with this mod
issueTrackerURL = "https://github.com/P3pp3rF1y/SophisticatedBackpacksCreateIntegration/issues" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks-create-integration" #optional

# License
license = "All Rights Reserved"

# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "logo.png" #optional

# A text field displayed in the mod UI
credits = "Created by P3pp3rF1y." #optional

# A text field displayed in the mod UI
authors = "P3pp3rF1y" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId = "sophisticatedbackpackscreateintegration" #mandatory

# The version number of the mod
version = "${mod_full_version}" #mandatory

# A display name for the mod
displayName = "Sophisticated Backpacks Create Integration" #mandatory

# The description text for the mod (multi line!) (#mandatory)
description = '''
Full Featured Sophisticated Backpacks on Create Contraptions
'''

[[dependencies.${mod_id}]]
modId="sophisticatedbackpacks"
mandatory = true #mandatory
versionRange="${sb_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory = true #mandatory
versionRange="${create_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
mandatory = false #mandatory
versionRange="${jei_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="forge"
mandatory = true #mandatory
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory = true #mandatory
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
